/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { NftCollectionFactory } from "./NftCollectionFactory";
export * as factories from "./factories";
export { NftCollectionFactory__factory } from "./factories/NftCollectionFactory__factory";
